[FEAT] main 글쓰기 페이지 마크업 추가 및 부 타이틀 제목 추가
FRONTENDBOOTCAMP-11th/DAEDDA pull request #15
Opened 2024-12-25 07:55 UTC by doyoung1002

## PR 유형

- [] 새로운 기능 추가
- [] 버그 수정
- [v] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제

## PR 체크리스트

- [v] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 상세

- main 글쓰기 페이지 마크업 추가

![image](https://github.com/user-attachments/assets/f51d5c8e-58c7-49ff-8ece-0cd81e73486b)

- PR 페이지 및 main 상세 페이지, 글쓰기 페이지 공통 타이틀 추가

![image](https://github.com/user-attachments/assets/cc3c6fb7-c937-4e6f-91f3-4a6b9b47b195)

## 이슈

resolves #4

2024-12-25 14:18 UTC, iamodh requested changes
1. layout 24 마진을 헤더 말고 페이지 전체를 div로 감싸고 padding으로 주는 건 어떨까요?

2.  타이틀 부분에 수평 정렬이 맞지 않아요. 뒤로가기 아이콘에 마진은 빼는 게 나을 것 같고, absolute 처리해서 위로 띄워야 할 것 같습니다.

3. 전체적인 레이아웃이나 폰트, 아이콘 사이는 모바일, 웹 환경에서도 모두 커 보여서 팀원들이랑 다시 상의해봐야 할 것 같네요.

수고 많으셨습니다 👍

2024-12-26 00:26 UTC, yeon1ee commented
- padding을 전체적으로 주는게 좋을 것 같습니다.

고생하셨습니다 😀

2024-12-30 00:37 UTC, yeon1ee commented
input maxLength 추가 부탁드립니다!

2024-12-30 00:39 UTC, JeonSuna approved these changes
수고하셨습니다

2024-12-30 04:04 UTC, merged